config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/toggle_theme', to: 'toggle_theme#change'

  get '/privacy', to: 'privacy#index'

  get '/licenses', to: 'license#index'

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/preferences.rb
class Preferences < ApplicationRecord
  belongs_to :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :preferences, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/license_controller.rb
class LicenseController < ApplicationController
  def index
  end
end

app/controllers/privacy_controller.rb
class PrivacyController < ApplicationController
  def index
  end
end

app/controllers/toggle_theme_controller.rb
class ToggleThemeController < ApplicationController
  def change
    if session[:dark_mode] == "dark"
      session[:dark_mode] = nil
    else
      session[:dark_mode] = "dark"
    end

    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_version
    `git log -1 --format=%ci | awk '{print $1}' | sed s/-/./g`.strip
  end

  def current_commit
    `git rev-list HEAD --max-count=1 --abbrev-commit`.strip
  end

  def current_branch
    `git branch | sed -n '/* /s///p'`.strip
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/license_helper.rb
module LicenseHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/toggle_theme_helper.rb
module ToggleThemeHelper
end

app/views/home/index.html.erb
<% content_for :title do %><%= t('mintube.popular') %> - MinTube<% end %>

<%= render partial: 'shared/feed_menu' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= content_for?(:title) ? yield(:title) : 'MinTube' %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="<%= session[:dark_mode].blank? ? "no" : session[:dark_mode] %>-theme">
    <span style="display:none" id="dark_mode_pref"><%= session[:dark_mode] %></span>
    <div class="pure-g">
        <div class="pure-u-1 pure-u-md-2-24"></div>
        <div class="pure-u-1 pure-u-md-20-24" id="contents">
          <div class="pure-g navbar h-box">
            <div class="pure-u-1 pure-u-md-4-24">
              <a href="<%= root_path %>" class="index-link pure-menu-heading">MinTube</a>
            </div>
            <div class="pure-u-1 pure-u-md-12-24 searchbar">
              <form class="pure-form" action="/search" method="get">
                <fieldset>
                  <input type="search" style="width:100%" name="q" placeholder="<%= t("mintube.search") %>" value="">
                </fieldset>
              </form>
            </div>
            <div class="pure-u-1 pure-u-md-8-24 user-field">
              <% if user_signed_in? %>
                <div class="pure-u-1-4">
                  <a id="toggle_theme" href="<%= toggle_theme_path %>" class="pure-menu-heading">
                    <% if session[:dark_mode] == "dark" %>
                      <i class="icon ion-ios-sunny"></i>
                    <% else %>
                      <i class="icon ion-ios-moon"></i>
                    <% end %>
                  </a>
                </div>
                <div class="pure-u-1-4">
                  <a id="notification_ticker" title="<%= t("mintube.subscriptions") %>" href="/feed/subscriptions" class="pure-menu-heading">
                    <i class="icon ion-ios-notifications-outline"></i>
                  </a>
                </div>
                <div class="pure-u-1-4">
                  <a title="<%= t("mintube.preferences") %>" href="/preferences" class="pure-menu-heading">
                    <i class="icon ion-ios-cog"></i>
                  </a>
                </div>
                <div class="pure-u-1-4">
                  <span></span>
                </div>
              <% else %>
                <div class="pure-u-1-3">
                  <a id="toggle_theme" href="<%= toggle_theme_path %>" class="pure-menu-heading">
                    <% if session[:dark_mode] == "dark" %>
                      <i class="icon ion-ios-sunny"></i>
                    <% else %>
                      <i class="icon ion-ios-moon"></i>
                    <% end %>
                  </a>
                </div>
                <div class="pure-u-1-3">
                  <a title="<%= t("mintube.preferences") %>" href="/preferences" class="pure-menu-heading">
                    <i class="icon ion-ios-cog"></i>
                  </a>
                </div>
              <% end %>
            </div>
          </div>

          <%= yield %>

          <footer>
            <div class="pure-g">
              <div class="pure-u-1 pure-u-md-1-3">
                <a href="https://github.com/mint-lgbt/mintube">
                  <%= t('mintube.copyright') %>
                </a>
              </div>
              <div class="pure-u-1 pure-u-md-1-3">
                <i class="icon ion-ios-wallet"></i>
                BTC: <a href="bitcoin:bc1qfhe7rq3lqzuayzjxzyt9waz9ytrs09kla3tsgr">bc1qfhe7rq3lqzuayzjxzyt9waz9ytrs09kla3tsgr</a>
              </div>
              <div class="pure-u-1 pure-u-md-1-3">
                <i class="icon ion-ios-wallet"></i>
                XMR: <a href="monero:41nMCtek197boJtiUvGnTFYMatrLEpnpkQDmUECqx5Es2uX3sTKKWVhSL76suXsG3LXqkEJBrCZBgPTwJrDp1FrZJfycGPR">Click here</a>
              </div>
              <div class="pure-u-1 pure-u-md-1-3">
                <a href="https://github.com/mint-lgbt/mintube/wiki">Documentation</a>
              </div>
              <div class="pure-u-1 pure-u-md-1-3">
                <i class="icon ion-logo-javascript"></i>
                <a rel="jslicense" href="<%= licenses_path %>">
                  <%= t('mintube.jslicense') %>
                </a>
                /
                <i class="icon ion-ios-paper"></i>
                <a href="<%= privacy_path %>">
                  <%= t('mintube.privfooter') %>
                </a>
              </div>
              <div class="pure-u-1 pure-u-md-1-3">
                <i class="icon ion-logo-github"></i>
                <%= t("mintube.curr_version") %> <%= "#{current_version}" %>-<%= "#{current_commit}" %> @ <%= "#{current_branch}" %>
              </div>
            </div>
          </footer>
        </div>
      <div class="pure-u-1 pure-u-md-2-24"></div>
    </div>
  </body>
</html>

app/views/license/index.html.erb
<h1><%= t('mintube.jslicensehead') %></h1>
<table id="jslicense-labels1">
  <tr>
    <td>community.js</td>

    <td>
      <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0</a>
    </td>

    <td>
      <a href="https://github.com/mint-lgbt/mintube/blob/master/app/javascript/packs/community.js"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>embed.js</td>

    <td>
      <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0</a>
    </td>

    <td>
      <a href="https://github.com/mint-lgbt/mintube/blob/master/app/javascript/packs/embed.js"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>notifications.js</td>

    <td>
      <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0</a>
    </td>

    <td>
      <a href="https://github.com/mint-lgbt/mintube/blob/master/app/javascript/packs/notifications.js"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>player.js</td>

    <td>
      <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0</a>
    </td>

    <td>
      <a href="https://github.com/mint-lgbt/mintube/blob/master/app/javascript/packs/player.js"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>silvermine-videojs-quality-selector.min.js</td>

    <td>
      <a href="http://www.jclark.com/xml/copying.txt">Expat</a>
    </td>

    <td>
      <a href="https://github.com/omarroth/videojs-quality-selector"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>sse.js</td>

    <td>
      <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache-2.0-only</a>
    </td>

    <td>
      <a href="https://github.com/mpetazzoni/sse.js"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>subscribe_widget.js</td>

    <td>
      <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0</a>
    </td>

    <td>
      <a href="https://github.com/mint-lgbt/mintube/blob/master/app/javascript/packs/subscribe_widget.js"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>theme.js</td>

    <td>
      <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0</a>
    </td>

    <td>
      <a href="https://github.com/mint-lgbt/mintube/blob/master/app/javascript/packs/themes.js"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>videojs-contrib-quality-levels.js</td>

    <td>
      <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache-2.0-only</a>
    </td>

    <td>
      <a href="https://github.com/videojs/videojs-contrib-quality-levels"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>videojs-http-source-selector.js</td>

    <td>
      <a href="http://www.jclark.com/xml/copying.txt">Expat</a>
    </td>

    <td>
      <a href="https://github.com/jfujita/videojs-http-source-selector"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>videojs-markers.js</td>

    <td>
      <a href="http://www.jclark.com/xml/copying.txt">Expat</a>
    </td>

    <td>
      <a href="https://github.com/spchuang/videojs-markers"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>videojs-overlay.js</td>

    <td>
      <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache-2.0-only</a>
    </td>

    <td>
      <a href="https://github.com/brightcove/videojs-overlay"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>videojs-share.js</td>

    <td>
      <a href="http://www.jclark.com/xml/copying.txt">Expat</a>
    </td>

    <td>
      <a href="https://github.com/mkhazov/videojs-share"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>videojs-vtt-thumbnails.js</td>

    <td>
      <a href="http://www.jclark.com/xml/copying.txt">Expat</a>
    </td>

    <td>
      <a href="https://github.com/omarroth/videojs-vtt-thumbnails"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>videojs-youtube-annotations.js</td>

    <td>
      <a href="https://www.gnu.org/licenses/gpl-3.0.html">GPL-3.0</a>
    </td>

    <td>
      <a href="https://github.com/afrmtbl/videojs-youtube-annotations"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>video.js</td>

    <td>
      <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache-2.0-only</a>
    </td>

    <td>
      <a href="https://github.com/videojs/video.js"><%= t('mintube.source') %></a>
    </td>
  </tr>

  <tr>
    <td>watch.js</td>

    <td>
      <a href="https://www.gnu.org/licenses/agpl-3.0.html">AGPL-3.0</a>
    </td>

    <td>
      <a href="https://github.com/mint-lgbt/mintube/blob/master/app/javascript/packs/watch.js"><%= t('mintube.source') %></a>
    </td>
  </tr>
</table>

app/views/privacy/index.html.erb
<% content_for :title do %>Privacy Policy - MinTube<% end %>

<div class="h-box">
  <h2>Privacy</h2>
  <p>
    This document concerns what data you provide to this website, the purpose of
    the data, how the data is stored, and how the data can be removed.
  </p>

  <h3>Data you directly provide</h3>
  <p>
    Data that you provide to the website for the purpose of the site's operation
    (for example: an account name, account password, or channel subscription)
    will be stored in the website's database until the user decides to remove
    it. This data will not be intentionally shared with anyone or anything.
  </p>
  <p>Information stored about a registered user is limited to:</p>
  <ul>
    <li>a list of session tokens for remaining logged in across devices</li>
    <li>
      the last time an account was updated (to provide accurate notifications)
    </li>
    <li>
      a list of video IDs identifying notifications from a user's subscriptions
    </li>
    <li>a list of channel UCIDs the user is subscribed to</li>
    <li>a user ID (for persistent storage of subscriptions and preferences)</li>
    <li>a json object containing user preferences</li>
    <li>a hashed password if applicable (not present on google accounts)</li>
    <li>
      a randomly generated token for providing an RSS feed of a user's
      subscriptions
    </li>
    <li>a list of video IDs identifying watched videos</li>
  </ul>
  <p>
    Users can clear their watch history using the
    <a href="/clear_watch_history">clear watch history</a> page.
  </p>
  <p>
    If a user is logged in with a Google account, no password will ever be
    stored. This website uses the session token provided by Google to identify a
    user, but does not store the information required to make requests on a
    user's behalf without their knowledge or consent.
  </p>

  <h3>Data you passively provide</h3>
  <p>
    When you request any resource from this website (for example: a page, a
    font, an image, or an API endpoint) information about the request may be
    logged.
  </p>
  <p>Information about a request is limited to:</p>
  <ul>
    <li>the time the request was made</li>
    <li>the status code of the response</li>
    <li>the method of the request</li>
    <li>the requested URL</li>
    <li>how long it took to complete the request.</li>
  </ul>
  <p>
    No identifying information is logged, such as the visitor's cookie,
    user-agent, or IP address. Here are a couple lines to serve as an example:
  </p>
  <pre><code>2019-01-19 16:37:47 +00:00 200 GET /api/v1/comments/xrlETJYzH-c?format=html&hl=en-US 1345.88ms
2019-01-19 16:37:53 +00:00 200 GET /vi/r5P-f5arPXE/maxres.jpg 1085.41ms
2019-01-19 16:37:54 +00:00 200 GET /watch 7.04ms</code></pre>
  <p>
    This website does not store the visitor's user-agent or IP address and does
    not use fingerprinting, advertisements, or tracking of any form.
  </p>
  <p>
    This website provides links to googlevideo.com to provide audio and video
    playback. googlevideo.com is owned by Google and is subject to their
    <a href="https://policies.google.com/privacy">privacy policy</a>.
  </p>

  <h3>Data stored in your browser</h3>
  <p>
    This website uses browser cookies to authenticate registered users. This
    data consists of:
  </p>
  <ul>
    <li>
      An account token to keep you logged into the website between visits, which
      is sent when any page is loaded while you are logged in
    </li>
  </ul>
  <p>
    This website also provides an option to store site preferences, such as the
    theme or locale, without an account. Using this feature will store a cookie
    in the visitor's browser containing their preferences. This cookie is sent
    on every request and does not contain any identifying information.
  </p>
  <p>
    You can remove this data from your browser by logging out of this website,
    or by using your browser's cookie-related controls to delete the data.
  </p>

  <h3>Removal of data</h3>
  <p>
    To remove data stored in your browser, you can log out of the website, or
    you can use your browser's cookie-related controls to delete the data.
  </p>
  <p>
    To remove data that has been stored in the website's database, you can use
    the <a href="/delete_account">delete my account</a> page.
  </p>
</div>

app/views/shared/_feed_menu.html.erb
<div class="feed-menu">
  <a href="/feed/subscriptions" class="feed-menu-item pure-menu-heading">
    <%= t('mintube.subscriptions') %>
  </a>
  <a href="/feed/playlists" class="feed-menu-item pure-menu-heading">
    <%= t('mintube.playlists') %>
  </a>
</div>